apiVersion: v1
kind: Service 

metadata:
  name: nip2


spec:
  type: NodePort
  selector:
    env: dev

  ports:
    - name: port1 
      port: 8080
      targetPort: 80 
      protocol: TCP
      nodePort: 37080

