apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv1

spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  nfs:
    path: /elastic1
    server: 172.31.32.176


---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv2

spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  nfs:
    path: /elastic2
    server: 172.31.32.176

---


apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv3

spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  nfs:
    path: /elastic3
    server: 172.31.32.176
