apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb1
  namespace: tproject
subjects:
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb2
  namespace: sproject
subjects:
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-write
  apiGroup: rbac.authorization.k8s.io


~                                              
