apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sproject
  name: pod-write
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tproject
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
                                    
