apiVersion: v1 
kind: Pod 

metadata:
  name: pod1 


spec:
  containers:
    - name: cont1
      image: nginx 
      volumeMounts:
        - name: vol1
          mountPath: /vishal
  volumes:
    - name: vol1
      emptyDir: {}      
