apiVersion: v1
kind: Pod

metadata:
        name: pod2
        labels:
                a: b
spec:
        containers:
                - name: cont1
                  image: nginx
                  env:
                    - name: username
                      valueFrom:
                        configMapKeyRef:
                          name: qwe
                          key: v1

                    - name: usernam1
                      valueFrom:
                        configMapKeyRef:
                          name: qwe
                          key: v2
